# Generated by Django 3.2 on 2023-03-15 08:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.BigIntegerField(blank=True, error_messages={'unique': 'A user with that phone number already exists.'}, null=True, unique=True, validators=[django.core.validators.RegexValidator('^989[0-3,0]\\d{8}$', 'Enter a valid mobile number', 'invalid')], verbose_name='mobile number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required, 30 characters or fewer, starting with letter, letters, digial number', max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z][a-zA-Z0-9_\\.]+$', 'Enter a valid username starting with a-z.This value may contain only letters, numbers and underscore characters', 'invalid')], verbose_name='username'),
        ),
    ]
